name: ${project.name}
version: ${build.number}
description: ${project.description}
author: md_5
website: ${project.url}

main: com.md_5.spigot.Spigot
loadbefore: [pvparena]

commands:
  restart:
    description: Restart the server
    permission: spigot.restart

permissions:
  spigot.restart:
    description: Allows restarting of the server
    default: op
